[features]
seeds = false
skip-lint = false
[programs.localnet]
nas_9 = "3zRWN1YxsE9TXFEFQGELDxfRXq947z63RuNodeNLvrmr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/coach/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
